'use client'

import { useLanguage } from '@/contexts/LanguageContext'
import { Nav } from '@/components/nav'
import { Footer } from '@/components/footer'
import { motion } from 'framer-motion'

const content = {
  en: {
    title: 'Terms of Service',
    lastUpdated: 'Last Updated: February 7, 2025',
    sections: [
      {
        title: '1. Acceptance of Terms',
        content:
          'By using AI Love Letters, you agree to these Terms of Service. If you do not agree, please do not use our service.',
      },
      {
        title: '2. Description of Service',
        content:
          'AI Love Letters provides an AI-assisted platform for creating personalized love letters. Our service uses artificial intelligence to help users express their feelings in written form.',
      },
      {
        title: '3. User Responsibilities',
        content:
          'You are responsible for your use of the service and any content you provide, including compliance with applicable laws, rules, and regulations. You should only provide content that you have the right to share.',
      },
      {
        title: '4. Content Ownership',
        content:
          'The love letters generated by our AI are your property. You are free to use, share, or modify them as you see fit. However, you grant us a license to use, store, and share the content you provide to operate and improve our services.',
      },
      {
        title: '5. Privacy and Data Usage',
        content:
          'We respect your privacy. All personal information and content you provide is used solely for generating your love letters. Please refer to our Privacy Policy for more details on how we collect, use, and protect your data.',
      },
      {
        title: '6. Prohibited Uses',
        content:
          'You may not use our service for any illegal or unauthorized purpose. You must not, in the use of the service, violate any laws in your jurisdiction (including but not limited to copyright laws).',
      },
      {
        title: '7. Disclaimer of Warranties',
        content:
          "Our service is provided 'as is' without any warranties, expressed or implied. We do not guarantee that the service will always be safe, secure or error-free, or that it will function without disruptions, delays or imperfections.",
      },
      {
        title: '8. Limitation of Liability',
        content:
          'To the fullest extent permitted by applicable law, AI Love Letters shall not be liable for any indirect, incidental, special, consequential or punitive damages, or any loss of profits or revenues.',
      },
      {
        title: '9. Changes to Terms',
        content:
          "We may update these terms from time to time. We will notify you of any changes by posting the new Terms of Service on this page and updating the 'Last Updated' date at the top of this page.",
      },
      {
        title: '10. Contact Us',
        content:
          'If you have any questions about these Terms, please contact us at: terms@ailoveletters.com',
      },
    ],
  },
  zh: {
    title: '服务条款',
    lastUpdated: '最后更新日期：2025年2月7日',
    sections: [
      {
        title: '1. 条款接受',
        content:
          '使用AI Love Letters即表示您同意这些服务条款。如果您不同意，请不要使用我们的服务。',
      },
      {
        title: '2. 服务描述',
        content:
          'AI Love Letters提供一个AI辅助的平台，用于创建个性化的情书。我们的服务使用人工智能帮助用户以书面形式表达他们的感受。',
      },
      {
        title: '3. 用户责任',
        content:
          '您对自己使用服务和提供的任何内容负责，包括遵守适用的法律、规则和法规。您应该只提供您有权分享的内容。',
      },
      {
        title: '4. 内容所有权',
        content:
          '我们的AI生成的情书是您的财产。您可以自由使用、分享或修改它们。但是，您授予我们使用、存储和分享您提供的内容的许可，以运营和改进我们的服务。',
      },
      {
        title: '5. 隐私和数据使用',
        content:
          '我们尊重您的隐私。您提供的所有个人信息和内容仅用于生成您的情书。有关我们如何收集、使用和保护您的数据的更多详细信息，请参阅我们的隐私政策。',
      },
      {
        title: '6. 禁止用途',
        content:
          '您不得将我们的服务用于任何非法或未经授权的目的。在使用服务时，您不得违反您所在司法管辖区的任何法律（包括但不限于版权法）。',
      },
      {
        title: '7. 免责声明',
        content:
          '我们的服务按&quot;原样&quot;提供，不提供任何明示或暗示的保证。我们不保证服务始终安全、可靠或无错误，也不保证它将在没有中断、延迟或缺陷的情况下运行。',
      },
      {
        title: '8. 责任限制',
        content:
          '在适用法律允许的最大范围内，AI Love Letters不对任何间接、偶然、特殊、后果性或惩罚性损害，或任何利润或收入损失负责。',
      },
      {
        title: '9. 条款变更',
        content:
          '我们可能会不时更新这些条款。我们将通过在此页面上发布新的服务条款并更新本页顶部的&quot;最后更新&quot;日期来通知您任何更改。',
      },
      {
        title: '10. 联系我们',
        content: '如果您对这些条款有任何问题，请通过以下方式与我们联系：terms@ailoveletters.com',
      },
    ],
  },
}

export default function Terms() {
  const { language } = useLanguage()

  return (
    <div className="min-h-screen flex flex-col">
      <div
        className="fixed inset-0 z-0"
        style={{
          backgroundImage: `
            linear-gradient(135deg, 
              #738fbd 0%,
              #a8c3d4 20%,
              #dbd6df 40%,
              #ecc6c7 60%,
              #db88a4 80%,
              #cc8eb1 100%
            )
          `,
          opacity: 0.3,
        }}
      />

      <Nav />

      <main className="flex-grow relative z-10 pt-20">
        <div className="container mx-auto px-4 py-8 max-w-4xl">
          <motion.h1
            className={`text-4xl font-bold mb-4 text-center ${language === 'en' ? 'font-serif' : 'font-serif-zh'}`}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
          >
            {content[language].title}
          </motion.h1>

          <motion.p
            className={`text-sm text-gray-600 mb-8 text-center ${language === 'en' ? 'font-literary' : 'font-serif-zh'}`}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.1 }}
          >
            {content[language].lastUpdated}
          </motion.p>

          {content[language].sections.map((section, index) => (
            <motion.section
              key={index}
              className="mb-8"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.1 * (index + 1) }}
            >
              <h2
                className={`text-2xl font-bold mb-4 ${language === 'en' ? 'font-serif' : 'font-serif-zh'}`}
              >
                {section.title}
              </h2>
              <p
                className={`text-lg leading-relaxed ${language === 'en' ? 'font-literary' : 'font-serif-zh'}`}
              >
                {section.content}
              </p>
            </motion.section>
          ))}
        </div>
      </main>

      <Footer />
    </div>
  )
}
